version: '3'

services:
  fluentd:
    image: fluent/fluentd-kubernetes-daemonset:v1.14.3-debian-elasticsearch7-1.0
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ${PWD}/fluentd/fluentdroutingerror.conf:/fluentd/etc/fluent.conf
      - ${PWD}/fluentd/log:/fluentd/log
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - http.host=0.0.0.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic


  kibana:
    image: kibana:8.6.1
    ports:
      - 5601:5601
    networks:
      - elastic

  rails:
    image: syntaxhacker/raillog:latest
    ports:
      - "3000"
    networks:
      - elastic
    environment:
      FLUENTD_HOST: fluentd
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  # nginx:
  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: loadbalancer
    networks:
      - elastic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rails
    restart: always

networks:
  elastic:

volumes:
  elasticsearch_data: