
# Separate Docker Compose file for nginx service
# Filename: nginx-compose.yml

version: '3'

services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: loadbalancer
    networks:
      - elastic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rails
    restart: always

networks:
  elastic:
